<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Dell-Namanmishar" ignored="0" name="restassuredtests" tests="23" failures="11" timestamp="2021-04-09T11:55:23 IST" time="9.667" errors="0">
  <testcase name="checkContentType" time="0.003" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkResponseBody" time="0.008" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkResponseTime" time="0.0" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkstatusLine" time="0.0" classname="com.employee.testCases.TC002_Get_Single_Employee_Data"/>
  <testcase name="checkResponseBody" time="0.002" classname="com.employee.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkResponseTime" time="0.0" classname="com.employee.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkStatusCode" time="0.0" classname="com.employee.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkstatusLine" time="0.001" classname="com.employee.testCases.TC001_Get_All_Employees"/>
  <testcase name="checkContentType" time="0.001" classname="com.employee.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.NullPointerException" message="Cannot invoke method getValue() on null object">
      <![CDATA[java.lang.NullPointerException: Cannot invoke method getValue() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at io.restassured.http.Headers$getValue$4.call(Unknown Source)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.header(RestAssuredResponseOptionsGroovyImpl.groovy:302)
at io.restassured.internal.RestAssuredResponseOptionsImpl.header(RestAssuredResponseOptionsImpl.java:126)
at com.employee.testCases.TC004_Put_Employee_Record.checkContentType(TC004_Put_Employee_Record.java:93)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseBody" time="0.004" classname="com.employee.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employee.testCases.TC004_Put_Employee_Record.checkResponseBody(TC004_Put_Employee_Record.java:51)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkResponseTime" time="0.001" classname="com.employee.testCases.TC004_Put_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employee.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [200] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [-1]
at com.employee.testCases.TC004_Put_Employee_Record.checkStatusCode(TC004_Put_Employee_Record.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkstatusLine" time="0.0" classname="com.employee.testCases.TC004_Put_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [null]
at com.employee.testCases.TC004_Put_Employee_Record.checkstatusLine(TC004_Put_Employee_Record.java:86)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkContentType" time="0.001" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <failure type="java.lang.NullPointerException" message="Cannot invoke method getValue() on null object">
      <![CDATA[java.lang.NullPointerException: Cannot invoke method getValue() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.header(RestAssuredResponseOptionsGroovyImpl.groovy:302)
at io.restassured.internal.RestAssuredResponseOptionsImpl.header(RestAssuredResponseOptionsImpl.java:126)
at com.employee.testCases.TC005_Delete_Employee_Record.checkContentType(TC005_Delete_Employee_Record.java:71)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseTime" time="0.001" classname="com.employee.testCases.TC005_Delete_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.001" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [200] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [-1]
at com.employee.testCases.TC005_Delete_Employee_Record.checkStatusCode(TC005_Delete_Employee_Record.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkstatusLine" time="0.001" classname="com.employee.testCases.TC005_Delete_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [null]
at com.employee.testCases.TC005_Delete_Employee_Record.checkstatusLine(TC005_Delete_Employee_Record.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
  <testcase name="checkContentType" time="0.0" classname="com.employee.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.NullPointerException" message="Cannot invoke method getValue() on null object">
      <![CDATA[java.lang.NullPointerException: Cannot invoke method getValue() on null object
at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:53)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.RestAssuredResponseOptionsGroovyImpl.header(RestAssuredResponseOptionsGroovyImpl.groovy:302)
at io.restassured.internal.RestAssuredResponseOptionsImpl.header(RestAssuredResponseOptionsImpl.java:126)
at com.employee.testCases.TC003_Post_Employee_Record.checkContentType(TC003_Post_Employee_Record.java:93)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseBody" time="0.001" classname="com.employee.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.employee.testCases.TC003_Post_Employee_Record.checkResponseBody(TC003_Post_Employee_Record.java:51)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase name="checkResponseTime" time="0.001" classname="com.employee.testCases.TC003_Post_Employee_Record"/>
  <testcase name="checkStatusCode" time="0.002" classname="com.employee.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [200] but found [-1]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [-1]
at com.employee.testCases.TC003_Post_Employee_Record.checkStatusCode(TC003_Post_Employee_Record.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase name="checkstatusLine" time="0.001" classname="com.employee.testCases.TC003_Post_Employee_Record">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [null]
at com.employee.testCases.TC003_Post_Employee_Record.checkstatusLine(TC003_Post_Employee_Record.java:86)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- checkstatusLine -->
</testsuite> <!-- restassuredtests -->
